apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-lost-in-hospital
  namespace: lost-in-hospital
spec:
  selector:
    matchLabels:
      app: deploy-lost-in-hospital
  replicas: 5
  template:
    metadata:
      labels:
        app: deploy-lost-in-hospital
    spec:
      containers:
      - name: deploy-lost-in-hospital
        image: puurl/alp-lost-hospital:v3
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        volumeMounts:
          - name: model
            mountPath: "/usr/src/app/model/"
      volumes:
        - name: model
          nfs: 
            server: 10.10.110.5
            path: /nfs_infra/pv-lost-in-hospital
