apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
<<<<<<< HEAD:lost-hospital.ddns.net/ingress-lost-hospital..yaml
  name: ingress-lost-in-hospital
  namespace: lost-in-hospital
=======
  name: ing-lost-hospital
  namespace: lost-hospital
>>>>>>> 0e0b8e64b8364d36acd87eae6e3f9dfef2a8d350:lost-hospital.ddns.net/ingress-lost-hospital.yaml
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: "lost-in-hospital.ddns.net"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: svc-lost-in-hospital
              port: 
                number: 8080
